name: "Lark pull request notify"
description: "A lark pull request notify of GitHub actions."
author: "zhecks"
inputs:
  notification_title:
    required: false
    description: "the title of notification"
    default: "${{ github.repository }}"

  users:
    required: true
    description: "the user mapping to the lark's open id, e.g. Alice|openID,Bob|openID"

  workflows_status:
    required: false
    description: "the status of workflows which you need to notify"
    default: "success"

  webhook:
    required: true
    description: "the lark robot webhook"

runs:
  using: "node16"
  main: "dist/index.js"
