name: "Lark pull request notify"
description: "A lark pull request notify of GitHub actions."
author: "zhecks"
inputs:
  notification_title:
    required: false
    description: "the title of notification"
    default: "${{ github.repository }}"
  
  token:
    required: false
    description: "it's neccessary for private repository, public repository also can use token to increase api's limit"

  users:
    required: true
    description: "the user mapping to the lark's open id, e.g. Alice|openID,Bob|openID"

  timeout:
    required: false
    description: "the timeout time which wait for other workflows"
    default: "1800"

  interval:
    required: false
    description: "the interval of polling"
    default: "15"

  webhook:
    required: true
    description: "the lark robot's webhook"

runs:
  using: "node16"
  main: "dist/index.js"
